// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftbulvkqljmquxnuexbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0YnVsdmtxbGptcXV4bnVleGJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTY2MjgsImV4cCI6MjA2NjI5MjYyOH0.PIUshC7aWVSCJBD8O4SXdMpa6l2iyUGPscNF4W2GPug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);